version: '3.1'

services:
  apache:
    build: .
    ports:
       # Use Reverse Proxy like nginx for production
      - 8088:80
    volumes:
      - ./app:/var/www/html/
    environment:
      DB_HOST: mysql
      DB_USER: root   

  mysql:
    image: mysql:5.7
    environment:
      # Change this Password on production
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    ports:
    # Disable on production
      - 8089:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      # Change this Password on production
      - PMA_PASSWORD=secret